# vpa-carts-db.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: carts-db-vpa
  namespace: sock-shop
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       carts-db
  updatePolicy:
    updateMode: "Auto"
