apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: orders-db-vpa
  namespace: sock-shop
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-db
  updatePolicy:
    updateMode: Auto
